version: '3'

services:

  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - .data/rabbitmq/rabbitmq1/data/:/var/lib/rabbitmq/
      - .data/rabbitmq/rabbitmq1/logs/:/var/log/rabbitmq/log
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: always

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - .data/rabbitmq/rabbitmq2/data/:/var/lib/rabbitmq/
      - .data/rabbitmq/rabbitmq2/logs/:/var/log/rabbitmq/log
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: always

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - .data/rabbitmq/rabbitmq3/data/:/var/lib/rabbitmq/
      - .data/rabbitmq/rabbitmq3/logs/:/var/log/rabbitmq/log
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: always

  rabbitmq4:
    image: rabbitmq:3-management
    hostname: rabbitmq4
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - .data/rabbitmq/rabbitmq4/data/:/var/lib/rabbitmq/
      - .data/rabbitmq/rabbitmq4/logs/:/var/log/rabbitmq/log
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: always

  rabbitmq5:
    image: rabbitmq:3-management
    hostname: rabbitmq5
    depends_on:
      - rabbitmq1
    environment:
      - JOIN_CLUSTER_HOST=rabbitmq1
    volumes:
      - ./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie
      - ./cluster-entrypoint.sh:/usr/local/bin/cluster-entrypoint.sh
      - .data/rabbitmq/rabbitmq5/data/:/var/lib/rabbitmq/
      - .data/rabbitmq/rabbitmq5/logs/:/var/log/rabbitmq/log
    entrypoint: /usr/local/bin/cluster-entrypoint.sh
    restart: always

  haproxy:
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq1
      - rabbitmq2
      - rabbitmq3
      - rabbitmq4
      - rabbitmq5
    ports:
      - 15672:15672
      - 5672:5672
      - 1936:1936
    restart: always
